# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  # TODO: Add hardware configuration for probook
  # This can be generated by running `sudo nixos-generate-config --show-hardware` on the machine.

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
